[build]
  base = "website/"
  command = "yarn build"
  publish = "public/"

[build.environment]
  NODE_VERSION = "14"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/bigtest/:splat"

[[redirects]]
  from = "/bigtest/interactors/*"
  to = "https://frontside.com/interactors/:splat"

[[redirects]]
  from = "/bigtest/docs/interactors/*"
  to = "https://frontside.com/interactors/docs/:splat"

[[redirects]]
  from = "/bigtest/platform"
  to = "/bigtest"  

[[redirects]]
  from = "/bigtest/docs/platform/*"
  to = "/bigtest/docs/:splat"

[[headers]]
  for = "/bigtest/asciinema/iframes/cross-platform.html"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
