[build]
  base = "website/"
  command = "yarn build"
  publish = "public/"

[build.environment]
  NODE_VERSION = "12"

[dev]
  command = "yarn start"
  publish = "public/"
  targetPort = 3000
  framework = "#custom"

[[redirects]]
  from = "/*"
  to = "/bigtest/:splat"

[[headers]]
  for = "/bigtest/asciinema/iframes/cross-platform.html"

  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
